blank_issues_enabled: false
contact_links:
  - name: Email Support / メールで問い合わせ
    url: mailto:support@hakaru.net
    about: Private contact (do not include personal info on GitHub Issues) / 非公開での連絡はこちら
